version: '3.8'

services:
  eureka-server:
    image: pankajbhatt/musy-eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=ec2
    networks:
      - musy-network

  api-gateway:
    image: pankajbhatt/musy-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=ec2
    networks:
      - musy-network

  auth-service:
    image: pankajbhatt/musy-auth:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=ec2
    networks:
      - musy-network

  user-service:
    image: pankajbhatt/musy-user:latest
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=ec2
    networks:
      - musy-network

  music-service:
    image: pankajbhatt/musy-music:latest
    container_name: music-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=ec2
    networks:
      - musy-network

  like-service:
    image: pankajbhatt/musy-like:latest
    container_name: like-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=ec2
    networks:
      - musy-network

  history-service:
    image: pankajbhatt/musy-history:latest
    container_name: history-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=ec2
    networks:
      - musy-network

  frontend:
    image: pankajbhatt/musy-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - musy-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api-gateway
      - frontend
    networks:
      - musy-network

networks:
  musy-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
