spring:
  application:
    name: history-service
  profiles:
    default: local
    group:
      prod:
        - ec2
  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:file:../.env[.properties]"
      - "optional:file:./history-service/.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jwt:
    secret: ${JWT_SECRETE_KEY}
    expiration-ms: ${JWT_EXPIRE:360000}

server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true