spring:
  config:
    import: "optional:file:./user-service/.env[.properties]"
  application:
    name: user-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    secret: ${JWT_SECRETE_KEY}
    expiration-ms: ${JWT_EXPIRE}

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
