spring:
  application:
    name: api-gateway-service
  profiles:
    default: local
    group:
      prod:
        - ec2
  codec:
    max-in-memory-size: 20MB
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOriginPatterns:
                  - "https://musy-pnkj.duckdns.org"
                  - "http://musy-pnkj.duckdns.org"
                  - "http://localhost:5173"
                  - "http://localhost:3000"
                  - "http://localhost:8080"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin  Access-Control-Allow-Credentials, RETAIN_FIRST
          httpclient:
            connect-timeout: 30000
            response-timeout: 120s

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG
