spring:
  config:
    import: "optional:file:./music-service/.env[.properties]"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jwt:
    secret: ${JWT_SECRETE_KEY}
    expiration-ms: ${JWT_EXPIRE}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: music-service

server:
  port: 8083

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
aws:
  s3:
    bucket: musys3-151963020801-ap-south-1-an
    region: ap-south-1
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
